name: My first pipeline

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: build image
              run: docker build -t jessicadjedje/ciportofolio .
            - name: List images
              run: docker images


    test:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo hello